-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "unitsPerCase" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "casesPerPallet" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shelfLife" TEXT;
